[build]
  bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe cmd/api/main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]

[log]
  time = true

[misc]
  clean_on_exit = true